# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test (misskey.js)

on:
  push:
    branches: [ steskey ]
  pull_request:
    branches: [ steskey ]

jobs:
  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - run: corepack enable

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        if: github.event_name != 'pull_request'
        run: pnpm i --frozen-lockfile

      - name: Install dependencies (PR)
        if: github.event_name == 'pull_request'
        run: pnpm i --no-frozen-lockfile

      - name: Check pnpm-lock.yaml
        run: git diff --exit-code pnpm-lock.yaml

      - name: Build
        run: pnpm --filter misskey-js build

      - name: Test
        run: pnpm --filter misskey-js test
        env:
          CI: true

      - name: Upload Coverage
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./packages/misskey-js/coverage/coverage-final.json
